import type { FichaPublica } from "./types"

export const SERVICIOS: FichaPublica[] = [
  {
    slug: "control-doc",
    grupo: "ordenar",
    nombre: "ControlDoc",
    frase:
      "Todos los documentos de tu personal, tu flota y tus contratistas en un solo lugar, con un semáforo que muestra qué está al día y qué no.",
    paraVos: [
      "Tenés contratistas o subcontratistas y tenés que pedirles documentación cada mes.",
      "Manejás personal o vehículos y no sabés qué papeles están vencidos.",
      "Hoy la documentación vive en carpetas, mails y WhatsApp.",
    ],
    incluye: [
      "Carga y revisión de documentos con lectura automática",
      "Aprobaciones con historial y versiones",
      "Semáforo de cumplimiento por persona, vehículo y empresa",
      "Tableros para ver el estado general de un vistazo",
    ],
    precioDesde: null,
    tipoCobro: "recurrente",
    publicado: true,
    paginaDetalle: "/control-doc",
  },
  {
    slug: "panel-remitos",
    grupo: "ordenar",
    nombre: "Panel de remitos",
    frase: "Cargá y consultá tus remitos desde un panel, sin planillas ni papeles sueltos.",
    paraVos: [
      "Emitís o recibís remitos todos los días y se te pierden entre papeles.",
      "Necesitás encontrar rápido un remito de hace meses.",
      "Querés evitar cargar dos veces el mismo remito.",
    ],
    incluye: [
      "Panel web para ver y buscar todos tus remitos",
      "Extensión para el navegador que carga los remitos desde el sistema que ya usás",
      "Aviso cuando un remito está repetido",
    ],
    precioDesde: null,
    tipoCobro: "mixto",
    publicado: true,
  },
  {
    slug: "conciliacion-bancaria",
    grupo: "ordenar",
    nombre: "Conciliación bancaria y de facturas",
    frase: "Cruzá tu extracto del banco con tus facturas y encontrá al instante lo que no coincide.",
    paraVos: [
      "Cada mes perdés horas comparando el banco con las facturas.",
      "Tenés cobros o pagos que no sabés a qué factura corresponden.",
      "Tu contador te pide la conciliación y la hacés a mano.",
    ],
    incluye: [
      "Carga del extracto del banco y de las facturas",
      "Cruce automático de movimientos con facturas",
      "Lista de diferencias para revisar",
    ],
    precioDesde: null,
    tipoCobro: "mixto",
    publicado: false,
  },
  {
    slug: "autocompletador-facturas",
    grupo: "ordenar",
    nombre: "Autocompletador de facturas",
    frase: "Subís la factura y el sistema completa los datos por vos.",
    paraVos: [
      "Cargás a mano los datos de decenas de facturas.",
      "Te equivocás al tipear CUIT o importes.",
      "Querés pasar las facturas a tu sistema contable sin volver a escribirlas.",
    ],
    incluye: [
      "Lectura de facturas en PDF o en foto",
      "Datos completados automáticamente para que solo revises",
      "Exportación a planilla",
    ],
    precioDesde: null,
    tipoCobro: "mixto",
    publicado: false,
  },
  {
    slug: "landing",
    grupo: "encontrar",
    nombre: "Página web completa",
    frase: "Tu página web lista para que te encuentren y te escriban.",
    paraVos: [
      "Tu negocio no tiene página o tiene una muy vieja.",
      "Querés que te contacten por WhatsApp desde Google o Instagram.",
      "Necesitás algo profesional sin armar un sitio gigante.",
    ],
    incluye: [
      "Diseño a medida de tu marca",
      "Botón de WhatsApp y formulario de contacto",
      "Preparada para aparecer en Google",
      "Publicación en tu propio dominio",
    ],
    precioDesde: null,
    tipoCobro: "unico",
    publicado: true,
  },
  {
    slug: "control-redes",
    grupo: "encontrar",
    nombre: "ControlRedes",
    frase: "Posts y reels para tus redes, hechos a la medida de tu negocio.",
    paraVos: [
      "No tenés tiempo de pensar qué publicar.",
      "Querés presencia en Instagram y Facebook sin contratar una agencia grande.",
      "Tu negocio tiene mucho para mostrar pero no sabés cómo.",
    ],
    incluye: ["Plan de contenido mensual", "Posts y reels pensados para tu rubro", "Material listo para publicar"],
    precioDesde: null,
    tipoCobro: "recurrente",
    publicado: false,
  },
  {
    slug: "asistente-virtual",
    grupo: "encontrar",
    nombre: "Asistente virtual por WhatsApp",
    frase: "Un asistente que atiende a tus clientes por WhatsApp y te ordena los pedidos.",
    paraVos: [
      "Te escriben por WhatsApp todo el día y no das abasto.",
      "Querés tomar pedidos sin atender cada mensaje a mano.",
      "Querés que tus clientes consulten precios y horarios sin molestarte.",
    ],
    incluye: [
      "Atiende por WhatsApp con la información de tu negocio",
      "Toma pedidos y los deja ordenados",
      "Te avisa cuando hace falta que intervenga una persona",
    ],
    precioDesde: null,
    tipoCobro: "mixto",
    publicado: false,
  },
  {
    slug: "jarvis-propio",
    grupo: "medida",
    nombre: "Tu propio asistente de inteligencia artificial",
    frase: "Un asistente de inteligencia artificial propio, al que le pedís tareas desde el celular o la compu.",
    paraVos: [
      "Querés usar inteligencia artificial en serio en tu trabajo pero no sabés armarla.",
      "Necesitás un asistente que recuerde tu contexto y tus proyectos.",
      "Querés delegar tareas repetitivas a una IA.",
    ],
    incluye: [
      "Tu propio espacio privado en nuestro servidor",
      "Acceso desde el celular o la computadora con tu PIN",
      "Memoria propia de tus proyectos",
    ],
    precioDesde: null,
    tipoCobro: "mixto",
    publicado: false,
  },
  {
    slug: "a-medida",
    grupo: "medida",
    nombre: "Sistema a medida",
    frase: "Un sistema hecho a tu medida para el problema que hoy te frena.",
    paraVos: [
      "Trabajás con planillas, papeles y WhatsApp y todo se desordena.",
      "Ningún programa del mercado hace exactamente lo que necesitás.",
      "Querés automatizar una tarea que se repite todos los días.",
    ],
    incluye: [
      "Una charla para entender cómo trabajás",
      "Propuesta con alcance y precio antes de empezar",
      "Desarrollo, puesta en marcha y soporte",
    ],
    precioDesde: null,
    tipoCobro: "unico",
    publicado: true,
  },
]
